### PR TITLE
Issue #44 play button feedback

### PR DESCRIPTION
**Pull request by femans**
this branch serves to make the play buttons in the audio detail view responsive to the status of the audio player.
On order to do this, some architectural change has been made.

Global audio events have been removed.
In stead, the audioplayer and its status are kept together in a single module that exposes observable variables.
A mixin adds this module and audio controls to a component.

### CODE REVIEW

**Comment by femans** [comment]
@dokterbob i think we need to update the eslint parser or something. Would you mind to run an update on that or ask me to do this? You can merge the branch if you think it is ok.

**Comment by dokterbob** [comment]
It seems that code climate is giving a lot of false errors because the linter config is not up to date. 

Could you please rebase to master to see if this resolves the issues?

**Comment by femans** [comment]
done @dokterbob

**Review by vandrongelen — APPROVED** [review]
I've some strange eslint warnings that has to do with sass. For some reason I am not able to remove them with the help of .eslintignore. Anyway this eslint stuff has nothing to do with this issue.

**Comment by dokterbob** [comment]
@femans There's conflicts again, please resolve them and I'll do a last check and we're ready to merge.

Please note that I rebased your code to master so I could discriminate your changes.

**Comment by femans** [comment]
its working now, can you test? @dokterbob

**Pull request merged**
