### PR TITLE
Feature/filetype filters

### PR DESCRIPTION
**Pull request by femans**
- Add subtype filters for file types.
- Add 'any' filetype that does not filter at all. replace 'any' title with 'all types'
- add support for markdown, spreadsheets, presentations
- make filter menu responsive; in small screens, its a menu
- fix pagination on small screens

### N.b. to reviewers
The choice for which mimetypes to include and how to organize them is based on

- opinion
- trial and error
- lots of research

remember that mimetypes are not always correct or implemented at al. There is no real central registry for mimetypes, some agencies make up their own without officially registering them, some are still in experimental stage, some are simply used throughout the internet without any official registration. Some filetypes go without mimetype or are simply marked as binary (`application/octet-stream`)

As such, I would suggest we can have a single round of feedback on which ones to include/exclude/split/combine now, and I will add it or not based on my personal opinion, and then we merge it. This is something that can and will be refined over time with more than 1 PR and discussion. In other words, I would like to merge this fast rather than perfect.

1 more thing; CodeClimate does not accept long files. I will take a look at fixing this either by fixing the definitions file or changning the CC rule

### CODE REVIEW

**Comment by femans** [comment]
Todo:

- [ ] fix unit tests
- [ ] fix styling of filters (they don't fit)
- [ ] add subtypes for images and for other

**Comment by dokterbob** [comment]
After a quick look: I would really suggest allowing filtering by specific types (e.g. Word documents, PDF, ePub) rather than a mixture of specific types (e.g. HTML and PDF) and categories (e.g. eBook). Also because some eBooks are PDF's etc. etc.

But THIS IS SUPER. Really, the biggest UX improvement this year (if you ask me).

**Comment by femans** [comment]
When merging we need some new features:
[] Filter reset function
[] visual indicator that filters have been applied / which

**Comment by dokterbob** [comment]
There's something weird going on with the build; gitlab fails while fleek doesn't, based on the exact same image! I'm looking into it...

**Comment by dokterbob** [comment]
First of all. MAAAAAN this is the best new feature we've had in years. Looking forward to this one for a while. Perhaps also one of the reasons I have my own ideas about it. Ideas, not demands. =)

# Reflections on last sucesful Fleek build

## File types and categories mixed.
image

As per screenshot, we have categories (groups of file types) and file types (extensions/mime types) mixed. This might or might not be a good idea, but I think it should be a well thought-over and consistent decision. I see several options:

### Mixed categories or not?
1. Keeping them mixed, but having categories before extensions, and ordered by prevalence in our dataset.
2. Adding a 'subtype' filter with these categories and, again, ordering them by prevalence and having a separate one for file types, also ordered by prevalence.
3. Removing categories for now, keeping the feature for later.

My personal preference (take it or leave it) would be 3. This is because some categories are really hard to define (see below). Please be aware that our goal is to use an API to retrieve available filter values for a particular query, so proper faceting. In this case categories also could proof problematic.

### Categories
In the case of 1/2, I would suggest defining them really well and adding the reasoning here as a comment for later reference. Based on the attached screenshot, I would suggest the following categories (not necessarily in order):

a. ... (PDF, DJVU)
b. Office documents (Word, OpenOffice Writer, RTF)
c. Presentations
d. Spreasheets
e. Books (ePub, Mobi, PRC)
f. Websites (HTML and xHTML)
g. Text (Markdown, text)
h. Code 
i. Vector (SVG, Postscript, Illustrator)

Note that there seems to be a semantic problem already around a., e. and i. I would consider PDF, DJVU and Postscript the same category (they represent stuff which can be replicated exactly in print) but I really can't find a word for it. Some PDF is vector, all DJVU is raster, all Postscript is vector. Similarly, many PDF's and DJVU documents are (scanned) books. In the near future, it would make a hell of a lot of sense to also add 'scientific publications', but they are determined based on completely different factors than mime types.

In addition, if we just have mime types, we can allow ourselves the luxury of searching for specific programming languages, or file types for specific ebook readers, which I personally would find awesome. Plus, I understand that most scientific papers are distributed in PDF, so I can find them. By far the most office documents are Word and the only alternative format is ODT, so in 2 queries I can find them.

Which begs the (open) question: is there an increased user benefit and if so, is it worth having complicated semantic discussions like these? ;)

### Extensions
I would suggest to use UPPERCASE for all extensions (e.g. PDF, JPEG), I personally feel that this is what users are used to. Also considering that most of them are acronyms. Lastly, it could be a way to create the distinction between categories and extensions in case of option 1.

Again, not a must more nice to have.

All in all, this is REALLY FUCKING SUPER. Just, so you know. :)

**Comment by dokterbob** [comment]
Small addition (for reference, copied from chat):
[Nee default is wat we hadden, een lijst met alle soorten. De ongefilterde heeft ook geen viewers enz](https://matrix.to/#/!wcWbkrSgWVMwnmaaWy:matrix.org/$VxshUd24Y-WlweHcPHESqp9-yKpXSw2ky83lYBgbhfs?via=matrix.org)
Oh. Ik zie het nu. Die feature is leuk, maar is qua gebruikersverwachting erg moeilijk te scheiden van 'All types'. Bovendien maakt een groter aantal keuzes hier gebruikers het leven moeilijk.

Wellicht dat er een anderen manier is om dit te doen, op een manier die explicieter is, of die zelfs een nadrukkelijke easter egg is.

**Comment by femans** [comment]
> Small addition (for reference, copied from chat): [Nee default is wat we hadden, een lijst met alle soorten. De ongefilterde heeft ook geen viewers enz](https://matrix.to/#/!wcWbkrSgWVMwnmaaWy:matrix.org/$VxshUd24Y-WlweHcPHESqp9-yKpXSw2ky83lYBgbhfs?via=matrix.org) Oh. Ik zie het nu. Die feature is leuk, maar is qua gebruikersverwachting erg moeilijk te scheiden van 'All types'. Bovendien maakt een groter aantal keuzes hier gebruikers het leven moeilijk.
> 
> Wellicht dat er een anderen manier is om dit te doen, op een manier die explicieter is, of die zelfs een nadrukkelijke easter egg is.

I am going to need this (non)-category for the 'clickable metadata' too. For this I will should ideally refactor the detailview slightly more, so that it looks at the mimetype to select what type of viewer to use.

**Comment by femans** [comment]
> First of all. MAAAAAN this is the best new feature we've had in years. Looking forward to this one for a while. Perhaps also one of the reasons I have my own ideas about it. Ideas, not demands. =)
> 
> # Reflections on last sucesful Fleek build
> ## File types and categories mixed.
> image
> 
> As per screenshot, we have categories (groups of file types) and file types (extensions/mime types) mixed. This might or might not be a good idea, but I think it should be a well thought-over and consistent decision. I see several options:
> 
> ### Mixed categories or not?
> 1. Keeping them mixed, but having categories before extensions, and ordered by prevalence in our dataset.
> 2. Adding a 'subtype' filter with these categories and, again, ordering them by prevalence and having a separate one for file types, also ordered by prevalence.
> 3. Removing categories for now, keeping the feature for later.
> 
> My personal preference (take it or leave it) would be 3. This is because some categories are really hard to define (see below). Please be aware that our goal is to use an API to retrieve available filter values for a particular query, so proper faceting. In this case categories also could proof problematic.
> 
> ### Categories
> In the case of 1/2, I would suggest defining them really well and adding the reasoning here as a comment for later reference. Based on the attached screenshot, I would suggest the following categories (not necessarily in order):
> 
> a. ... (PDF, DJVU) b. Office documents (Word, OpenOffice Writer, RTF) c. Presentations d. Spreasheets e. Books (ePub, Mobi, PRC) f. Websites (HTML and xHTML) g. Text (Markdown, text) h. Code i. Vector (SVG, Postscript, Illustrator)
> 
> Note that there seems to be a semantic problem already around a., e. and i. I would consider PDF, DJVU and Postscript the same category (they represent stuff which can be replicated exactly in print) but I really can't find a word for it. Some PDF is vector, all DJVU is raster, all Postscript is vector. Similarly, many PDF's and DJVU documents are (scanned) books. In the near future, it would make a hell of a lot of sense to also add 'scientific publications', but they are determined based on completely different factors than mime types.
> 
> In addition, if we just have mime types, we can allow ourselves the luxury of searching for specific programming languages, or file types for specific ebook readers, which I personally would find awesome. Plus, I understand that most scientific papers are distributed in PDF, so I can find them. By far the most office documents are Word and the only alternative format is ODT, so in 2 queries I can find them.
> 
> Which begs the (open) question: is there an increased user benefit and if so, is it worth having complicated semantic discussions like these? ;)
> 
> ### Extensions
> I would suggest to use UPPERCASE for all extensions (e.g. PDF, JPEG), I personally feel that this is what users are used to. Also considering that most of them are acronyms. Lastly, it could be a way to create the distinction between categories and extensions in case of option 1.
> 
> Again, not a must more nice to have.
> 
> All in all, this is REALLY FUCKING SUPER. Just, so you know. :)


So, you only looked at the documents type filter, ok. My rationale was: if you look for spreadsheets, you don't want to run multiple queries because of different office software packs. Whereas if you look for publications, you usually look for PDF. 
I was considering putting epub and ebook together but wasn't sure. For the rest, I suggest we just try out for now how it feels while using, you can always shoot in an issue or PR with a different layout of the filter. From all your message I only took that I will place PDF below the office stuff. 

'Code' is now categorized under 'Other'. It is hard to find a comprehensive list of code-mimetypes, so if you have this, this would be welcome. Currently there are only mimetypes for Java, javascript, python, shell scripts, fortran and assembly, most of them experimental stage mimetypes, and only java files turn up. It would be an interesting feature in the future to have an extra filter besides code for specifically which language. But that is beyond the scope of this PR.

**Comment by dokterbob** [comment]
Based on your feedback, my proposal would be:
* Do not show the 'Other' type by default, but keep it there to allow metadata linking.
* Keep category filters as they are for now and ignore how it felt for me using (referring to 'I suggest we just try out for now how it feels while using, you can always shoot in an issue or PR with a different layout of the filter. '), and if you will allow me I'd like to make a PR with some of my suggested changes myself.

* That way we can get the PR in with minimal additional efforts and have the benefit of this feature.

**Comment by femans** [comment]
image
@Szeket found this bug, this needs to be fixed

**Comment by femans** [comment]
Ok I refactored to fix the xl responsiveness and leave out the 'unfiltered' category in the menu.

**Comment by Szeket** [comment]
> Ok I refactored to fix the xl responsiveness and leave out the 'unfiltered' category in the menu.

yes, now is responsive :)

**Pull request merged**
