### PR TITLE
Inter Planetarify

### PR DESCRIPTION
**Pull request by femans**
# Planitarify - 
turn the interplanetary filesystem into your personal audio center 

### bugs:

- [x] loading errors give an alert on next song #241 
- [x] scrolling goes beyond screen size - both search and playlist
- [x] search bar homepage responsiveness

### styling: 

- [x] app bar on small screen has too much stuff. Type selector should be in filter dropdown
- [x] app bar should turn searchbar into magnify-icon and when you click that, go back to search view
- [x] Search view tiles stretch if text gets too long. Text needs to be cropped
- [x] responsiveness of major features

### features:

- [x] show artists, albums, trackNr on second line in playlist
- [ ] show duration in playlist on the right #242
- [x] remove song from playlist function
- [ ] enqueue song in detail view #243
- [x] 'show song details'
- [ ] (NTH) drag/drop change order #244
- [x] auto-skip songs which had loading error before
- [x] (NTH) loop function
- [ ] (NTH) shuffle function #245
- [x] when clicking 'play all', go to playlist view
- [ ] (NTH) integrate system audio controls #246

### CODE REVIEW

**Comment by dokterbob** [comment]
# Planetarians Unite! 

It works over crappy 4G+++

Some issues, none of them blocking a merge (but wise to create issues before merge):
image

This could be a rectangle (stop button) not a cross (close button):
image

This could be the cross/close button:
image

Suggestion: making these amazing buttons less attention-attracting. Specifically; less colour. I feel they distract from content:
image

Could be something like https://next.vuetifyjs.com/en/components/buttons/#outlined or any of these https://next.vuetifyjs.com/en/components/buttons/#variant

**Comment by femans** [comment]
The strategy, I think, is: to launch this feature with along with a communication blast. 
Maybe after midi functionality is ready too, so this can be added too. 

Note that there are some bugs and Nice To Have features still on the list, which I will turn into issues. These are not blocking the release in my opinion.

**Comment by dokterbob** [comment]
Quick last review, all suggestions are purely optional:

- [ ] Instead of blinking play button, change the play button into a pause button for the currently playing item in the list.
image

- [ ] The back button doesn't go to the previous track. Rather, it starts the same song again.
image

- [ ] Not sure whether a stop button is necessary at all. How is the functionality different from the stop button?
image

- [ ] It would be *so fucking awesome* if clicking on an artist's name or an album would link to the search results for that artist or album, exactly like the metadata search.

- [ ] Palette-wise, @Szeket has a point. The purple is quite intense. Perhaps we can use one of the lighter colours from `theme.js`?

**Comment by femans** [comment]
> I think it's cool! Very nice feature! I have few questions though:
> 
> I think the lines outlining "audio", "documents", "video" etc. are too thick. Could they be thinner and also have the same colour as lines from filters? To somehow refer to it graphically? 
They are the minimum width, 1px, and I like them. Matter of opinion. They have the ipfsPrimary color. 

> This song is gray once I listen to it? 
The song is grey if there is an error, usually it does not load or it has an unplayable format. Probably should indicate this better with a warning icon/error tooltip
 
> Why do I get this error? Any ideas?
Yeah it is a bug and it has been reported already ,#241
I may fix it still after I am a bit ahead with the other projects.

> I am not a big fan of the violet background colour. I think the ipfs-search.com theme is blue-gray, so maybe we can make this colour a bit less intense and more relating to the theme palette?
Again, matter of opinion, but I wanted something more alive and fun than black (which it was first) or those greyish colors. Also I wanted to let it stand out a bit by itself, like you go to a different realm or app within ipfs-search.com. So I looked for deep purple. I can try looking for a deeper shade of purple, if it is still too much, but I did try it on different screens with different color settings.

**Comment by femans** [comment]
@dokterbob 
> Quick last review, all suggestions are purely optional:
> 
> * [ ]  Instead of blinking play button, change the play button into a pause button for the currently playing item in the list.

Could be, but i don't know why. A case could be made for a better indicator of which entry is currently playing. But that wouldn't be it. 

> * [ ]  The back button doesn't go to the previous track. Rather, it starts the same song again.

That is a bug I think, I encountered it sometimes but couldn't recreate it, so I didn't make an issue.

> * [ ]  Not sure whether a stop button is necessary at all. How is the functionality different from the stop button?

It is no different than the stop button because it is the stop button... I am sure I am not understanding the question. 

> * [ ]  It would be _so fucking awesome_ if clicking on an artist's name or an album would link to the search results for that artist or album, exactly like the metadata search.

There is a little disc icon on the right that brings you to detail view of that song. It is slightly buggy and there should be made some issues about this. E.g., from that detail view, metadata search does not work properly.

> * [ ]  Palette-wise, @Szeket has a point. The purple is quite intense. Perhaps we can use one of the lighter colours from `theme.js`?

> * [ ]  The difference in the border which @Szeket mentioned seems to be a difference in colour. The filters have a hover to black and are lighter. It would indeed be great to have them behave similarly to the filters (include the hover, actually).

No, the filter are dropdowns, these are buttons/banners. If anything, the filters' appearance should be changed, to match the ipfs-search colors. 

It would be great if... not having these discussions in the PR about everything that would be great. 
Thanks for the feedback though  👯

**Review by dokterbob — CHANGES_REQUESTED** [review]
# Blocking issue
## Freeze when selecting audio from home page
(Tested on 5eac544d42f6bb1b02491dc28eefd614f9970f96)
When on home page, click on the search button or select any type but images (no need to enter a search query, but doing so results in the same behaviour).
image

Now the site freezes (the spinner is not running):
image

image

**Comment by femans** [comment]
fixed the blocking issue

**Pull request merged**
