### PR TITLE
Reuse

### PR DESCRIPTION
**Pull request by NSfsfe**
Hello,

By way of introduction, I am Niharika Singhal from the Free Software Foundation Europe, and the REUSE Booster program. Thank you for contacting us and we are happy to help you out with the implementation of REUSE. After a check on your repository, I would like to propose some updates regarding your copyright and licensing information. The REUSE specifications intend to make licensing easier with best practices to display legal information through comment headers on source files that can be easily human and machine readable. You can check this screencast:
https://download.fsfe.org/videos/reuse/screencasts/reuse-tool.gif

Please keep in mind that this merge request is intended to be a practical example of how REUSE looks like.

I would also like to make some remarks to be considered to make your full project REUSE compliant.

Feel completely free to adopt these specifications by merging this pull request.
**REUSE Features:**

SPDX copyright and license comment headers for all relevant files (please be aware that in the current state of the repository, I was able to add headers to all the directories. However, some files might miss this feature depending on the type of the file. For example, .nvmrc  file.) If you are interested in implementing REUSE specification, I hope this merge request can help you to do so.
**LICENSES directory in the root of the project with the licenses used on the repository:**

I included in this directory, the file that contained the license for your project (AGPL 3.0 only) text. If some pieces of your project use a different license, please add their license text to the LICENSES directory.
**Files missing copyright and licensing information:**

I noticed that your project does not have the copyright and license information displayed in a comment header. According to the REUSE specifications, the comment headers MUST contain the SPDX Tag. For this, we recommend to update the headers, or at least the SPDX-License-Identifier as in this practical example.

Please also double check if the personal information in the headers is correct and consistent, in the case of several copyright holders please update that information in the headers.

In case you want to license certain files under a different license, special attention should also be paid to that aspect and such files should contain the appropriate SPDX tag.

Please note that I used the REUSE helper tool to add the headers, so the tool automatically deleted the existing header (if any) and changed it to the SPDX format.

**#Image files in the .reuse directory in the root of the project:**
Copyright and Licensing Information MAY be associated with a file through a DEP5 file that you will find in the .reuse folder in the root of the project. The intended use case of this method is large directories where including a comment header in each file (or in .license companion files) is impossible or undesirable. I added the AGPL.v.03 only license to all of the image files. However, you can license other image files under licenses as well and include the license in the LICENSES directory.
We can also do a follow up of this PR and further REUSE specification with a call. Feel free to reach me out.

Hope that helps and thank you very much for the amazing job!

Niharika Singhal - Trainee
Free Software Foundation Europe
Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290
Registered at Amtsgericht Hamburg, VR 17030 | https://fsfe.org/support

### CODE REVIEW

**Comment by dokterbob** [comment]
Hi, thanks! This is great!

It does seem there is an issue with the build, we will have to check this out (it might be on our side). 

Is there any chance you might add a short reference (e.g. paragraph) of documentation to internally propagate how to keep these practises, so that we can continue them (e.g. 2/3 sentences explaining how and why of SPDX headers and perhaps a link to a bit of the how/why of this)?

As we're usually more focused on building rather than legalities, this is a great help. Thanks!

**Comment by NSfsfe** [comment]
Hi!

I am very happy to hear that this was helpful to you. :)

So this is the basic content by FSFE on the REUSE Software which gives a good overview of it for those who want to get acquainted with the same: https://reuse.software/

This page highlights all the specifications of the REUSE Software. For instance, what is the SPDX License Identifier or what is a Dep5 file and why it is useful to have the same in your project. In short, this document guides you on what steps are to be taken to make your project legally compliant with the necessary licensing and copyright information.: https://reuse.software/spec/

And finally, this page solves all your technical problems.:https://reuse.readthedocs.io/en/stable/readme.html

Should you have a specific query, please do not hesitate to reach out to me.

All the best!

Niharika Singhal - Trainee
Free Software Foundation Europe
Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290
Registered at Amtsgericht Hamburg, VR 17030 | https://fsfe.org/support

**Comment by dokterbob** [comment]
Hi @NSfsfe, build seems to be fixed (we remove the pnpm lock file). 

Would you be able to manually rebase from master (`git rebase master && git push -f`) or (if rebase fails) `git merge master` and/or resolve the merge conflict? 

Thanks!

**Comment by dokterbob** [comment]
> Hi!
> 
> I am very happy to hear that this was helpful to you. :)
> 
> So this is the basic content by FSFE on the REUSE Software which gives a good overview of it for those who want to get acquainted with the same: https://reuse.software/
> 
> This page highlights all the specifications of the REUSE Software. For instance, what is the SPDX License Identifier or what is a Dep5 file and why it is useful to have the same in your project. In short, this document guides you on what steps are to be taken to make your project legally compliant with the necessary licensing and copyright information.: https://reuse.software/spec/
> 
> And finally, this page solves all your technical problems.:https://reuse.readthedocs.io/en/stable/readme.html
> 
> Should you have a specific query, please do not hesitate to reach out to me.
> 
> All the best!
> 
> Niharika Singhal - Trainee Free Software Foundation Europe Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290 Registered at Amtsgericht Hamburg, VR 17030 | https://fsfe.org/support

Thanks Niharika, that's great! Would you perhaps be able to make this additional information part of your PR? For example, adding to the licensing section in the README or adding a `LICENSING.md` file in the main directory, or something else if you find that more appropriate. It would be great if this info doesn't get lost.

Thanks!

**Comment by NSfsfe** [comment]
Hi,

As requested, I have added a file containing all the important links to the REUSE Software.

All the best!

Niharika Singhal - Trainee Free Software Foundation Europe Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290 Registered at Amtsgericht Hamburg, VR 17030 | https://fsfe.org/support

**Comment by dokterbob** [comment]
Hi @NSfsfe,

Thanks! Could you please let me know if you would be able to resolve the merge conflicts so that we can merge your PR?

Thanks!
M

**Comment by NSfsfe** [comment]
Hi @dokterbob 

I have made the requisite changes. Does it look fine to you now?

Best,
Niharika

**Comment by dokterbob** [comment]
Hi @NSfsfe,

It does seem there are still some linter errors. We have a policy that whenever files are changed, they have to comply with our formatting standards. You can run these tests locally with: `npm run lint` and you can automatically try to fix them with `eslint --fix` (you might have to install eslint with `npm i -g eslint`).

If you don't manage I can do this but you but I usually prefer going the didactic route. ;)

In addition, I noticed that you marked the used webfonts as AGPL. However, I think they're actually Apache licensed. https://fonts.google.com/specimen/Roboto#license 

Thanks for your patience! :)
Mathijs

**Comment by NSfsfe** [comment]
Hi @dokterbob 

To be very frank with you, I am a lawyer and there is a high probability that I can definitely get lost with the test instructions that you have mentioned. If there is a possibility, I would request you to make the make the requisite corrections at your end. :)

Regarding the webfonts, I marked the files with an AGPL license information since visibly, the whole project carried the AGPL license. However, now that you have pointed out, I have changed the Roboto webfonts to Apache license with the required copyright information. But you can always change the license and copyright information using the REUSE helper tool for the other webfonts and files. Please ensure to include the complete license of the files in the directory marked as LICENSES in the root of the project like I have included the Apache 2.0 license now.

Hope this helps!

Best,
Niharika

**Comment by dokterbob** [comment]
Superseded by #215 (current PR with lint fixups). 

❤️❤️❤️ to @NSfsfe and the FSFE :)

**Comment by NSfsfe** [comment]
Hi Mathijs,

Thank you so very much for all your encouraging words. It means a lot to me and the FSFE! :D
We are extremely delighted that we could be of some help to your project, so please continue doing the great work.
And of course your kind words on our annual report will encourage not only our team but also other developers to use the REUSE tool to incorporate the best practices for displaying licensing and copyright information into their projects.

Many thanks once again and wish you all the best,
Niharika

**Comment by femans** [comment]
hi @NSfsfe, thank you so much for this initiative. We are discussing the correct file headers. Would something like this be valid/appropriate?
`SPDX-FileCopyrightText: 2020-2022, IPFS-search <info@ipfs-search.com>`

**Comment by NSfsfe** [comment]
Hi @femans 

Indeed the accurate copyright information is something you know better depending on the type of arrangement you have internally. The merge request was just to demonstrate what at the outset the copyright field could look like. If you are wanting to replace Mathijs' name from the copyright information with IPFS-search, then you should use this command:

SPDX-FileCopyrightText: 2022 IPFS-search <info@ipfs-search.com>

SPDX-License-Identifier: AGPL-3.0-only

Dweb-search-frontend

While doing so, do make sure that you use appropriate comment headers for each file type.
 
Alternatively, using the REUSE tool makes everything easier and convenient and I encourage you to do so to avoid any errors. The command in that case should be:

reuse addheader --copyright="2022 IPFS-search, <info@ipfs-search.com>." --license=AGPL-3.0-only --year=2022  --skip-unrecognised *file path*

Hope this helps!

Best,
Niharika

**Pull request closed without merging**
