### PR TITLE
Other type search

### PR DESCRIPTION
**Pull request by femans**
Add an 'Other' function to the improved filters branch, for searching files that do not have any of the whitelisted mimetypes.

### CODE REVIEW

**Comment by dokterbob** [comment]
Super great to have this!

I rebased from 80c5975 but might have thrown away some patches/bugfixes.

I would suggest we first find a solution for #194 and then merge this one and/or add it to this PR. Or, if it's not blocking, we could merge as-is.
@femans What do you think?

**Comment by dokterbob** [comment]
One strong suggestion: please actuallu use 'Other'. Files comes across to me as very confusing!

**Comment by dokterbob** [comment]
It could be 'other files' if you insist, but I think 'Other' should be clear enough to users, whereas files... is not.

**Comment by dokterbob** [comment]
@femans Please rebase from master so I can see what actual changes exist between this branch and master, there are currently 78 commits in this PR.

**Review by dokterbob — CHANGES_REQUESTED** [review]
Code looks good to me, but no results are returned when I search for... cheese.

This PR:
image


Master:
image

**Review by dokterbob — CHANGES_REQUESTED** [review]
Now there are duplicate results:
image

Also, the file type is not shown for Other, which is probably more relevant there than anywhere else.

**Comment by femans** [comment]
> Now there are duplicate results: image
> 
> Also, the file type is not shown for Other, which is probably more relevant there than anywhere else.

fixed.

**Pull request merged**
